### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by jmalkin** [apache/datasketches-python#25]
Most/all our methods have docstrings, but @leerho commented to me at some point that we don't have the larger class descriptions anywhere. We obviously need to fix that.

Since docstrings at the class level will appear multiple times where we have `kll_ints_sketch`, `kll_floats_sketch`, and `kll_items_sketch`, we should have a general description in the .rst used for sphinx when generating our gh-docs info. The description tied to the actual class, which would show up in a call like `help(kll_items_sketch)` can be a single line.

**Comment by jmalkin** [comment]
Both #27 and #28 have contributed to this

**Comment by c-dickens** [comment]
Also we do not yet have the rst pages for any of the sampling sketches.

**Comment by jmalkin** [comment]
Sampling pages are in an open PR

**Comment by jmalkin** [comment]
That's merged now. Let's see if I can get the multi-level thing looking ... i guess the benchmark is "better than now"

**Comment by jmalkin** [comment]
I think #31 will be sufficient to close out this issue

**Comment by jmalkin** [comment]
We can always improve documentation, but that PR has been merged and our documentation is so, so much better than before. Declaring victory on this particular issue and closing it.
