### ISSUE TITLE
Numpy 2 support

### ISSUE THREAD

**Issue by mcgrawia** [apache/datasketches-python#49]
Hi datasketch team,

We recently upgraded to numpy 2 and have ran into the following exception in our logs. It seems like data sketches only supports numpy 1? What will it take to add numpy 2 support?

Thanks

Full error
```
A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.1.1 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "<string>", line 1, in <module>
  File "/app/repositories/metrics_repository.py", line 9, in <module>
    from datasketches import kll_floats_sketch
  File "/lib/python3.12/site-packages/datasketches/__init__.py", line 26, in <module>
    from _datasketches import *
Traceback (most recent call last):
  File "/lib/python3.12/site-packages/numpy/core/_multiarray_umath.py", line 44, in __getattr__
    raise ImportError(msg)
ImportError:
A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.1.1 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.
```

**Comment by jmalkin** [comment]
As far as I know, nothing! It should work if you remove the version restriction.

Several years ago we were hit with an error when a new python came out numpy hadn't upgraded to use that. Since then we've been pinning versions to avoid unexpected gotchas. But in this case, we have.. I think exactly 1 call to a numpy API and that one didn't change to 2.0.

If you build from source it should work to just remove the version restriction. But it's been enough months that we should be able to safely move -- except that it'll also be a major version bump since it can cause incompatibility when integrating our library, even if our own API doesn't change!

We added bloom filter support in C++ so maybe I'll try to get that added to this package so it feels like our major version has something beyond the numpy version change. But if I can't get that done quickly then maybe we'll just do a version bump in isolation.

**Comment by jmalkin** [comment]
Oops, the bloom filter isn't released in C++ yet. Ok, I'll see what people think of a new release just for numpy.

**Comment by jmalkin** [comment]
And look at that -- I even had a branch ready. Turns out there was 1 incompatible call in a test that was a trivial fix.

**Comment by mcgrawia** [comment]
Thanks @jmalkin! Appreciate the quick turn around on this

**Comment by mcgrawia** [comment]
@jmalkin I see the MR is merged, do you know when it would be possible to trigger a release? 

#50

**Comment by jmalkin** [comment]
Apache has a Process for releases. Working on starting that process now, but I just kicked off the task to create wheels (which I imagine is the main way people get the library) and that's probably not going to finish before my night ends. So I'll try to kick off process on Tuesday (US Pacific Time).

**Comment by jmalkin** [comment]
Found I had not fully removed the version constraint on numpy so new PRs to fix that, both in the release branch and main. Then I get to recreate the wheels.

**Comment by jmalkin** [comment]
Apologies. The wheels took a very long time to build (specifically musllinux cross-compiled for ARM64, which took over 4 hours; the other sets of wheels took at most about 35 mins) and real life intruded for a couple days. Should get a release vote out tonight (US Pacific Coast time) and it needs to be open for at least 72 hours not including weekends.

**Comment by mcgrawia** [comment]
ok thanks for the update. I'll keep an eye out early next week for a release

**Comment by jmalkin** [comment]
A day later than intended, but the latest release should be up on pypi now.

When I tested locally by installing the correct wheel, it imported successfully whether I had numpy 1.x or 2.x installed.

Gonna close this, but obviously feel free to reopen if there's a problem.

**Comment by mcgrawia** [comment]
thanks @jmalkin! Testing with the new release now and confirmed the numpy incompatibility is gone 👍
